version: 2

jobs:
  build:
    docker:
      - image: node:8-stretch
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y xvfb # xvfb for running headless tests (headless X11 server).
      - run: apt-get install -y libgirepository1.0-dev libgtk-3-dev # system dependencies for node-gir and GTK
      - run: npm install
      - run: npm run lint
      - run: xvfb-run -a npm run test
